
FROM python:3.11 AS base

FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY /backend/requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

FROM base
ENV FLASK_APP main.py
WORKDIR /project
COPY --from=builder /install /usr/local
ADD ./backend/api /project

ENTRYPOINT ["python3", "-m", "flask", "run", "--host=0.0.0.0"]
