import { AuthContextProvider } from '@/app/_components/AuthProvider'
import type { Metadata } from 'next'
import './global.css'


export const metadata: Metadata = {
  title: 'TrendSet',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='m-8'>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
